#!/usr/bin/bash

repomd_file=$1

if [[ ! -f "${repomd_file}" || $(basename ${repomd_file}) != 'repomd.xml' ]]; then
    echo -e "Usage:\n  $(basename $0) [PATH]repomd.xml " 1>&2
    exit 1
fi

set -e
declare -a tiers
shopt -s nullglob extglob

repomd_fmt="$(dirname ${repomd_file})/repomd-t%s.xml"
tiers=( $(dirname ${repomd_file})/repomd-t+([0-9]).xml )

for ((ti=${#tiers[@]}-1; ti>0; ti--)); do
    cp --preserve=timestamps $(printf "${repomd_fmt} ${repomd_fmt}"  $((ti - 1)) ${ti} )
done